[package]
name = "img2irc-rs"
version = "1.0.6"
authors = ["waveplate"]
github = "https://github.com/waveplate/img2irc"
repository = "https://github.com/waveplate/img2irc"
description = "CLI utility to convert images to halfblock ANSI or IRC art with various optional post-processing filters"
license = "GPL-3.0-only"
readme = "README.md"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true  # Automatically strip symbols from the binary.

[[bin]]
name = "img2irc"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls"] }
photon-rs = { version = "0.3.2", default-features = false, git = "https://github.com/silvia-odwyer/photon", rev = "3b72d357848cd76be9363e87ad0cd02a19b988d2" }
clap = { version = "4.2.0", features = ["cargo", "derive"] }
url = "2.3.1"

[build-dependencies]
cc = "1.0"
