[package]
name = "img2irc-rs"
version = "1.1.1"
authors = ["waveplate"]
github = "https://github.com/waveplate/img2irc"
repository = "https://github.com/waveplate/img2irc"
description = "CLI utility to convert images to halfblock ANSI or IRC art with various optional post-processing filters"
license = "GPL-3.0-only"
readme = "README.md"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true  # Automatically strip symbols from the binary.

[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"

[[bin]]
name = "img2irc"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = "0.11.14"
photon-rs = { version = "0.3.2", default-features = false, git = "https://github.com/silvia-odwyer/photon", rev = "3b72d357848cd76be9363e87ad0cd02a19b988d2" }
#photon-rs = "0.3.2"
clap = { version = "4.2.0", features = ["cargo", "derive"] }
url = "2.3.1"
atty = "0.2.14"

[target.'cfg(target_env = "musl")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
